<template>
  <Dashboard>
    <Card class="flex flex-col items-start px-6 py-8 mb-8 bg-gradient-to-tr from-blue-700 to-blue-400">
      <h1 class="text-2xl font-bold text-white">Refer customers, get paid.</h1>
      <p class="max-w-2xl mt-1 text-base text-white">
        Start advertising your unique affiliate link. If someone signs up after visiting your link, you’ll receive 30% of all subscription revenue
        generated by this customer.
      </p>
      <router-link :to="{ name: 'AffiliateLink' }">
        <Button text="Share your link →" theme="white/blue" class="mt-3" />
      </router-link>
    </Card>
    <TabsBar class="mb-8" />
    <router-view />
  </Dashboard>
</template>

<script lang="ts" setup>
import Card from '../../components/Card/Card.vue'
import Dashboard from '../../layouts/Dashboard.vue'
import Button from '../../components/Button/Button.vue'
import TabsBar from '../../components/TabsBar/TabsBar.vue'
</script>
